### database ###
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ### hibernate ###
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  ### mail ###
  mail:
    host: smtp.gmail.com
    port: 587
    username: learn.mike.helloworld@gmail.com
    password: tugoutumkwlgxrpl
    protocol: smtp
    tls:
      enable: true